### ISSUE TITLE
Taunt message doesn't show properly.

### ISSUE THREAD

**Issue by ghost** [AnDwHaT5/PixelUtilities#11]
Upon using the move "taunt", "taunt.taunted" is displayed in the message area for the battle. 
"%s fell for the taunt!" is what should be displayed instead according to the pokemon games. From my thoughts, this should be a simple change to en_Us.lang

**Comment by clienthax** [comment]
Wrong repo, post on the pixelmon bug tracker http://pixelmonmod.com/tracker.php?p=2
